[versions]
lifecycle = "2.9.3"
material = "1.13.0-alpha11"
preference = "1.2.1"
shizuku = "13.1.0"
libsu = "6.0.0"
glide = "4.16.0"
lottie = "6.6.4"
gson = "2.12.1"
work = "2.10.1"
circleimageview = "3.1.0"
javax-annotation = "1.3.2"
junit = "4.13.2"

[libraries]
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }
libsu-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
javax-annotation = { module = "javax.annotation:javax.annotation-api", version.ref = "javax-annotation" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "work" }
junit = { module = "junit:junit", version.ref = "junit" }