name: Crowdin Upload Translations

on:
  workflow_dispatch:

jobs:
  upload-translations:
    name: Upload Android translations to Crowdin
    if: github.repository_owner == 'DP-Hridayan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload translations
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: true
          download_translations: false
          create_pull_request: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
